name: Gradle release and publish

on:
  release:
    types: [created]

jobs:
  releaseAndPublish:

    runs-on: ubuntu-latest
    environment: admin
    permissions:
      contents: write
      packages: write

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Extract version from tag
      id: extract_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    - name: Update version in version file
      run: |
          echo $VERSION > version

    - name: Build with Gradle
      run: ./gradlew build

    - name: Publish to Maven Central
      run: ./gradlew publishToMavenCentral
      env:
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralUsername }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralPassword }}
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKey }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKeyPassword }}
        
    - name: Increment minor version
      run: ./gradlew incrementMinorVersion

    - name: Commit version change
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "Tim van Oijen"
        git config user.email "timvanoijen@gmail.com"
        git add version
        git commit -m "Update version after Github release ${VERSION}"
        git push origin HEAD:main
